### ISSUE TITLE
Bad responsive design on mobile

### ISSUE THREAD

**Issue by SrBlimp** [UdL-EPS-SoftArch/softarch-1617-client#56]
![problem](https://cloud.githubusercontent.com/assets/16940773/21353897/510a49c0-c6c8-11e6-98cc-0dbc5e3c77c0.png)

Bad responsive design. :disappointed_relieved:

**Comment by Jap9** [comment]
Now looks good on 250% zoom

![ggg](https://cloud.githubusercontent.com/assets/17140922/21452791/a703cf98-c909-11e6-82d1-380d8883b6dc.PNG)
