### ISSUE TITLE
Message username should be taken on form display

### ISSUE THREAD

**Issue by SrBlimp** [UdL-EPS-SoftArch/softarch-1617-client#62]
It's currently taken in the constructor but it would be better to retrieved on form creation.

**Comment by Jap9** [comment]
![aaa](https://cloud.githubusercontent.com/assets/17140922/21451594/7f37377e-c900-11e6-9218-0c11786d8a28.PNG)

@SrBlimp  Username of the sender is taken from the message entity, in the form I dispay de name of the logged one if the sender field does not match the current logged user, it displays an alert (but that was another bug)
Do you mean to directly show in the HTML the logged user without setting it in the constructor?

**Comment by zurfyx** [comment]
@Jap9 Username should be retrieved as late as possible, or even not display it at all. After all, it is the server who should be taking care of this.
If the logged in user changes for whatever reason, it will not update on your component and the user will be seeing a wrong sender until the component reloads (after exiting and entering back).
