### ISSUE TITLE
Message should display an error if user didn't fill in all fields

### ISSUE THREAD

**Issue by zurfyx** [UdL-EPS-SoftArch/softarch-1617-client#63]
Currently you can submit, like if it was the success case, even if you didn't fill in anything in the form. The message does not get recorded into the server (that is fine), but the user does not get any visual notification about it.

**Comment by Jap9** [comment]
Now user gets an alert dialog if one or more fields are empty when trying to send message
(not pushed yet)

**Comment by zurfyx** [comment]
@Jap9 Use [close #issue](https://help.github.com/articles/closing-issues-via-commit-messages/) in your commit message instead. It will close automatically and will reference the commit which fixed it.
