### ISSUE TITLE
Nested URLs (/)

### ISSUE THREAD

**Issue by zurfyx** [UdL-EPS-SoftArch/softarch-1617-client#8]
Current router seems to be failing with URLs containing nested **/** (i.e. **advertisements/new**).

It tries to get .js resources from a relative path rather than absolute, which results in:

[development mode]
http://localhost:4200/advertisements/inline.js (instead of http://localhost:4200/inline.js)
http://localhost:4200/advertisements/main.bundle.js (instead of http://localhost:4200/main.bundle.js)
http://localhost:4200/advertisements/styles.bundle.js (instead of http://localhost:4200/styles.bundle.js)

Correct (at http://localhost:4200/advertisements):
![routing-good](https://cloud.githubusercontent.com/assets/193447/19221319/344a43b8-8e41-11e6-8fe5-03e7686fd19c.png)

Wrong (at http://localhost:4200/advertisements/new):
![routing-bad](https://cloud.githubusercontent.com/assets/193447/19221318/344986a8-8e41-11e6-9d19-4306a14a517c.png)

**Comment by rogargon** [comment]
This seems to happen just if you put the URL directly in the browser, if you navigate through links generated using routerLink it works fine. 

However, it should be working with direct URL too to enable bookmarking... so it seems a bug

**Comment by zurfyx** [comment]
Upgrading to Angular 2.1 fixed it. Commit @rogargon https://github.com/UdL-EPS-SoftArch/softarch-1617-client/commit/1f7329309b83258ea13ba36a6898bfe1bd9e8d64
